### ISSUE TITLE
 CommonRcvAdapter的onBindViewHolder 方法里面直接用mItemType，没调用getItemViewType，会不会有问题？

### ISSUE THREAD

**Issue by c1024** [tianzhijiexian/CommonAdapter#13]
```
@Deprecated
    @Override
    public int getItemViewType(int position) {
        mItemType = getItemType(mDataList.get(position));
        return mUtil.getIntType(mItemType);
    }

    @Override
    public Object getItemType(T t) {
        return -1; // default
    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return new RcvAdapterItem(parent.getContext(), parent, createItem(mItemType));
    }

    @SuppressWarnings("unchecked")
    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        debug((RcvAdapterItem) holder);
        ((RcvAdapterItem) holder).item.handleData(getConvertedData(mDataList.get(position), mItemType), position);
    }


```

@tianzhijiexian CommonRcvAdapte的onBindViewHolder 方法里面直接用mItemType，没调用getItemViewType，会不会有问题？

**Comment by kaleai** [comment]
你可以测试一下onBindViewHolder调用前都会自动调用一次，getItemType方法。这个和listview的getItemType不同。
rcv的流程是：
在onCreateViewHolder前调用getItemType方法来得到item的类型，将类型传入onCreateViewHolder(ViewGroup parent, int viewType)中

在onBindViewHolder 前会调用一次getItemType来得到类型。

测试结果：
![qq 20160225112431](https://cloud.githubusercontent.com/assets/9552155/13308913/b2e50506-dbb2-11e5-92e6-c7d5af625579.png)

![qq 20160225111958](https://cloud.githubusercontent.com/assets/9552155/13308823/bcc652d8-dbb1-11e5-8d77-2f7bb7be6f25.png)

**Comment by kaleai** [comment]
如果觉得有问题也可以测试一下看看，谢谢你的指出。我可以去排查下别的地方会不会有这个问题

**Comment by c1024** [comment]
截图里面的那个方法我这边源码看不到，我的RecycleView版本也是23.1.1。我这边bindViewHolder是在getViewForPosition里面调用。奇怪，都是同一版本。
截图如下：
![Image of Yaktocat](http://i.imgur.com/rZO53QN.png)

**Comment by kaleai** [comment]
这个你可以在代码里面测试一下吧，看看最终的结果。这样靠谱一点。

**Comment by gyh** [comment]
ListViewTestActivity 中将listView.setAdapter(test01(data)); 替换为listView.setAdapter(test02(data));，发现在 createItem 中出错，type为null

**Comment by kaleai** [comment]
已经找到了这个问题，正在解决@gyh

**Comment by kaleai** [comment]
@gyh问题是我在CommonAdapter构造方法中，忘记传了一个item的类型数目，你写上3就行。我稍后会改下demo。

new CommonAdapter<DemoModel>(data, 3)

这个是demo的问题，不是库的问题。所以没什么影响，同时谢谢你的反馈。我以后会强制传递一个count。

如果解决了你的问题，你可以close掉这个问题

**Comment by kaleai** [comment]
在最新的demo中已经解决了这个问题，请验证
