### ISSUE TITLE
如果不同的item数据结构不一样怎么处理

### ISSUE THREAD

**Issue by limboc** [tianzhijiexian/CommonAdapter#15]
demo中的imageview,buttonview,textview都是DemoModel

**Comment by kaleai** [comment]
1.把不同的数据模型放入同一个list<object>中
2.通过adapter中getConvertData来根据不同的type来给item分发数据

这样的做法是保证入口就是一个list，而运行list中的内容可以分化

具体可以参考：
https://github.com/tianzhijiexian/CommonAdapter/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fkale%2Fcommonadapter%2FListViewTestActivity.java
