### ISSUE TITLE
RcvAdapter自动刷新错位问题

### ISSUE THREAD

**Issue by fg2q1q3q** [tianzhijiexian/CommonAdapter#16]
## 代码如下，这是联网请求获取数据成功后的回调，根据类型(首次请求/下拉刷新/加载更多)来设置数据源。

> - 由于adapter只提供了setData方法设置数据，因此在下拉刷新和加载更多我想要插入/删除数据的时候只能自己重新组装出一个List来setData，多有不便，建议adapter增加addData和removeData的公共方法
> - 在版本更新说明中有提到“支持适配器的数据自动绑定，只用操作数据便可自动notify界面”，基于这点我把代码中最后一行的notify注释掉，结果出现数据错位问题，反复上下滑动列表几次才会显示正常，放开注释就一切正常，还请查证原因，谢谢
> 
> ``` python
>  public void onData(List<Book> books) {
>                 if (books == null) return;
>                 switch (refreshType) { // 设置新的数据
>                     case TYPE_NORMAL:
>                         adaper.setData(books);
>                         break;
>                     case TYPE_REFRESH:
>                        /*实际是这样的：重新组装数据源
>                         List a = adaper.getData();
>                         a.addAll(0, books);
>                         adaper.setData(a);*/
>                         // adaper.addData(0, books);期望是这样的
>                         recyclerView.refreshComplete();
>                         break;
>                     case TYPE_LOADMORE:
>                         List b = adaper.getData();
>                         b.addAll(adaper.getItemCount(), books);
>                         adaper.setData(b);
>                        // adaper.addData(adaper.getItemCount(), books);
>                         recyclerView.loadMoreComplete();
>                         break;
>                 }
>                 adaper.notifyDataSetChanged(); // 通知数据刷新
>             }
> ```

**Comment by kaleai** [comment]
问题1：在设计方案中adapter和数据是脱离的，并且我希望的是在代码中不维持一个全局的adapter。所以希望是对对于传入的list进行操作，而list是有addAll方法的。之所以不设置adapter的那么多add方法一个是处于代码复杂度方面的考虑，一个是出于adapter本身就是适配器，对于数据的操作还是交给数据对象来做。虽然我们通常用arraylist，但不能确保所有都是arraylist，也不能保证我增加的方法都能满足需要。

问题2：针对新版本中的东西，我会监听data的改变，然后进行相应的操作。具体的代码如下：

``` java
data.addOnListChangedCallback(new ObservableList.OnListChangedCallback<ObservableList<T>>() {
            @Override
            public void onChanged(ObservableList<T> sender) {
                notifyDataSetChanged();
            }

            @Override
            public void onItemRangeChanged(ObservableList<T> sender, int positionStart, int itemCount) {
                notifyItemRangeChanged(positionStart, itemCount);
            }

            @Override
            public void onItemRangeInserted(ObservableList<T> sender, int positionStart, int itemCount) {
                notifyItemRangeInserted(positionStart, itemCount);
            }

            @Override
            public void onItemRangeMoved(ObservableList<T> sender, int fromPosition, int toPosition, int itemCount) {
                // Note:不支持一次性移动"多个item"的情况！！！！
                notifyItemMoved(fromPosition, toPosition);
            }

            @Override
            public void onItemRangeRemoved(ObservableList<T> sender, int positionStart, int itemCount) {
                notifyItemRangeRemoved(positionStart, itemCount);
            }
        });
```

你调用了addData方法肯定会操作到onItemRangeInserted方法，这里有个rcv自己设计方面的问题。这个问题是如果仅仅调用onItemRangeInserted不调用notifyItemRangeChanged就会出现你所说的状况。这个是rcv自己的问题，但是我会在这个库里面进行处理的。处理方式也很简单，我稍后就会提交。

感谢你的测试，后面的问题是我之前没有发现，所以疏忽了。

**Comment by fg2q1q3q** [comment]
根据建议，将数据操作放进model里面，清爽不少，感谢

``` python
 if (books == null) return;
                switch (refreshType) { // 设置新的数据
                    case TYPE_NORMAL:
                        adaper.setData(books);
                        break;
                    case TYPE_REFRESH:
                        Book.addData(adaper.getData(), 0, books);
                        recyclerView.refreshComplete();
                        break;
                    case TYPE_LOADMORE:
                        Book.addData(adaper.getData(), adaper.getItemCount(), books);
                        recyclerView.loadMoreComplete();
                        break;
                }
                adaper.notifyDataSetChanged(); // 通知数据刷新
```

**Comment by kaleai** [comment]
问题已经修复，请查看
