### ISSUE TITLE
问题：觉得AdapterModel 的getDataTypeCount()好像多余

### ISSUE THREAD

**Issue by cooliean** [tianzhijiexian/CommonAdapter#2]
觉得AdapterModel 的getDataTypeCount()好像多余，总觉得没有用，修改了效果业是一样，能说说当初设计这个的初衷不呢。Demo中给，那个返回是3，随便修改效果业是一样，没有两样，感到很疑惑

**Comment by kaleai** [comment]
这个是adapter中的重要属性啊，来设置adapter中的item个数的。你可以去看看adapter的知识，一下子就理解啦

**Comment by cooliean** [comment]
我以为是返回你有多少个类型的不通的Item个数呢。Adapter的getItemCount，我知道

**Comment by thinwonton** [comment]
@cooliean 
是返回列表的类型数，不是item数目
作者是假设该列表有多个type的布局
你如果只需要一种布局，可以抽取一个SingleTypeAdapterModel
作者的真实意思是，假设这个列表是goodList，假设有3种布局类型
1/  BaseGoodListModel extend AdapterModel
并且  getDataTypeCount ---->3
2、GoodListModeType1  extend BaseGoodListModel
GoodListModeType2  extend BaseGoodListModel
GoodListModeType3  extend BaseGoodListModel
并在getDataType 返回各自的类型
3、创建三种类型布局的TypeAdapterItem extend AdapterItem
      映射list item的布局

**Comment by cooliean** [comment]
@mooncafes
恩，后来看明白了，谢谢，那个值在Recycler下面是没有用的，在ListView下面<1是要异常，但是只要大于1，随便什么值好像都是可以的，后来看到BaseAdapter里面是有那么一个属性的。但是还是没有理解到真正的好处，谢谢你

**Comment by kaleai** [comment]
如果解决了您的问题，可以由您来关闭这个问题
