### ISSUE TITLE
虽然可以为layout_item的父布局加一个id去setOnclickListener，但是感觉不够优雅

### ISSUE THREAD

**Issue by Andecy** [tianzhijiexian/CommonAdapter#20]
作者有什么更好的想法吗？

或者比如加一个默认的OnItemClick回调？

**Comment by kaleai** [comment]
现在在bind的时候能拿到root对象，给它设置就行了。如果觉得不够优雅，可以说说看你的想法吧。来吧

**Comment by cooliean** [comment]
这个我也考虑过的，怎么弄都不好弄，你回调的时候还要传对应的ID，还不如直接在那里设置了好了。组合EventBus，因为有一个ITEM里面多个按钮处理不同点击事件的可能。不知道说的怎么样，我觉得没有必须再在这个思路下面下功夫了，还有在优化方面比较好。

**Comment by kaleai** [comment]
eventbus不应该是首选，复杂度会高，正如你说的，目前还没有啥好的办法。
