### ISSUE TITLE
说明提到“支持适配器的数据自动绑定，只用操作数据便可，adapter会自动notify界面”

### ISSUE THREAD

**Issue by Andecy** [tianzhijiexian/CommonAdapter#21]
但是我看好像不会啊，我是没有用dataBinding的，而是用的butterknife。

我在一开始将adapter用null的data创建了，然后listview.setadapter，拿到数据之后我再adapter.setData，然而ListView并没有反应

**Comment by kaleai** [comment]
如果没有用databinding的obserableList，那么就不能实现这个效果了。

**Comment by kaleai** [comment]
如果没有用databinding的obserableList，那么就不能实现这个效果了。

**Comment by kaleai** [comment]
示例在demo中有，如果找到了并且了解了原理，那么可以过来关闭此问题。

**Comment by Andecy** [comment]
看到了，谢谢
