### ISSUE TITLE
bindViews似乎会加载多次，在这里用butterknife等注入工具会降低性能吗？

### ISSUE THREAD

**Issue by Andecy** [tianzhijiexian/CommonAdapter#22]
打了Log看了下，发现如果有多少行数据，那个函数就会执行多少次，这样会降低性能吗？

**Comment by kaleai** [comment]
bindview是不会加载多次的，你可以试试你放入100条数据，你就放一个item，然后看看log的数目是多少，可以尝试一下，如果仍旧是100次，那么就是我的严重失误了。咱们可以一起来看看

**Comment by Andecy** [comment]
# 我稍微所以下我是怎么用的：

AdapterItem：

```
@Override
public int getLayoutResId() {
    return R.layout.item_note;
}

@Override
public void bindViews(View view) {
    KLog.w();//打Log
    x.view().inject(this, view);//注入
}

@Override
public void handleData(Note note, int i) {
    tv_title.setText(note.getName());
}
```

# 

Fragment:

```
private CommonAdapter<Note> noteAdapter = new CommonAdapter<Note>(null, 1) {
    @NonNull
    @Override
    public AdapterItem createItem(Object o) {
        return new NoteItem();
    }
};
```

......

//加载到数据
                mListView.setAdapter(noteAdapter);
                noteAdapter.setData(taskNotes);
                noteAdapter.notifyDataSetChanged();

**Comment by kaleai** [comment]
嗯，好。然后看log

**Comment by Andecy** [comment]
04-08 10:10:36.008 26640-26640/com.andecy.exercise W/NoteItem.java: [ (NoteItem.java:48)#BindViews ] execute
04-08 10:10:36.018 26640-26640/com.andecy.exercise W/NoteItem.java: [ (NoteItem.java:48)#BindViews ] execute
04-08 10:10:36.038 26640-26640/com.andecy.exercise W/NoteItem.java: [ (NoteItem.java:48)#BindViews ] execute
04-08 10:10:36.058 26640-26640/com.andecy.exercise W/NoteItem.java: [ (NoteItem.java:48)#BindViews ] execute
04-08 10:10:36.078 26640-26640/com.andecy.exercise W/NoteItem.java: [ (NoteItem.java:48)#BindViews ] execute
04-08 10:10:36.088 26640-26640/com.andecy.exercise W/NoteItem.java: [ (NoteItem.java:48)#BindViews ] execute

**Comment by Andecy** [comment]
总共有6条数据，bindVIews执行了6次

**Comment by kaleai** [comment]
你放100条。

**Comment by Andecy** [comment]
好吧，意思是说这个bindViews会执行屏幕允许的item数量的次数吗？

**Comment by Andecy** [comment]
那这样的话，也会有一定性能上的影响吧，比如一个页面有十几个item的（不知道gridview会不会这样）

**Comment by kaleai** [comment]
是的，这个是listview本身的复用逻辑。这个和性能无关，这是必须的。我给你发一个我写的简单介绍，你看看就明白了：http://www.cnblogs.com/tianzhijiexian/p/4769959.html

**Comment by Andecy** [comment]
恍然大悟，非常感谢耐心解答！
