### ISSUE TITLE
使用CommonRcvAdapter时不引用databinding包会编译失败

### ISSUE THREAD

**Issue by xxxifan** [tianzhijiexian/CommonAdapter#23]
项目中没有引用databinding包，就会提示ObserverList找不到，我代码这样使用

`
 mList = new ArrayList<>();
 mAdapter = new CommonRcvAdapter<DeviceModel>(mList) {
            @NonNull
            public AdapterItem createItem(Object o) {
                return new DeviceItem();
            }
        };
        mRecyclerView.setAdapter(mAdapter);
`

就提示错误了，app的build.gradle导入了provided 'com.android.databinding:baseLibrary:1.0'才能通过编译，有没有办法不让我自己导这个包的？因为项目没有用到这个包

**Comment by kaleai** [comment]
我的错，我忘记更新readme了，其实如果不引入databinding也是可以的。你只需要添加一个假的databind依赖就行:
            compile 'com.github.tianzhijiexian:CommonAdapter_Fake_DataBinding:1.0.0'

**Comment by kaleai** [comment]
我明天更新下文档

**Comment by xxxifan** [comment]
ok, thanks

**Comment by kaleai** [comment]
暂时先不关闭这个issue，等我更新好了我交给你验证后进行关闭，因为那个fake库我可能还要发一个版本。

**Comment by kaleai** [comment]
库项目已经更新，请验证：https://github.com/tianzhijiexian/CommonAdapter-Fake-DataBinding

**Comment by kaleai** [comment]
readme也已经更新，请查看。我会想想办法让是否依赖databinding都能走一条依赖，不需要添加额外的依赖源。

**Comment by xxxifan** [comment]
刚刚1.0.0版本我试了下是可以的 明天再来试试1.0.1行不行
感谢

**Comment by kaleai** [comment]
我更新了下依赖的名字和版本，你重新依赖一下：

```
dependencies {
    compile 'com.github.tianzhijiexian:CommonAdapter-Fake-DataBinding:1.0.1'
}
```

**Comment by xxxifan** [comment]
测试可用 ;)

**Comment by xxxifan** [comment]
不对  我怎么用  带下划线的1.0.1  编译通过了  而你上面贴的带横刚的版本不行

**Comment by kaleai** [comment]
你clear下progect然后再试试

**Comment by kaleai** [comment]
我这里可以给出原始的远程地址：https://jitpack.io/com/github/tianzhijiexian/CommonAdapter-Fake-DataBinding/1.0.1/    

**结果：**

```
CommonAdapter-Fake-DataBinding-1.0.1.aar
CommonAdapter-Fake-DataBinding-1.0.1.pom
CommonAdapter-Fake-DataBinding-1.0.1.pom.md5
CommonAdapter-Fake-DataBinding-1.0.1.pom.sha1
build.log
```

**日志信息：**
Start: Sun Apr 10 15:23:46 UTC 2016
Git:
1.0.1
commit 8ac0f93adb7aa7ab0457168c836930c3cf3fff73
Author: kale 
Date:   Sun Apr 10 23:18:00 2016 +0800

```
删除了无用的代码，精简了库
```

submodule status:
Run gradle build
Gradle build script
Found gradle version: 2.10.
Using sdkman gradle
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

---

## Gradle 2.10

Build time:   2015-12-21 21:15:04 UTC
Build number: none
Revision:     276bdcded730f53aa8c11b479986aafa58e124a6

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_76 (Oracle Corporation 24.76-b04)
OS:           Linux 3.14.32-xxxx-grs-ipv6-64 amd64

0m0.480s
Getting a list of gradle tasks
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Found android library build file in lib
Running: gradle clean -Pgroup=com.github.tianzhijiexian -Pversion=1.0.1 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Download https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.3/android-maven-gradle-plugin-1.3.pom
Download https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/1.3/android-maven-gradle-plugin-1.3.jar
Gradle version Gradle 2.10
Incremental java compilation is an incubating feature.
:clean UP-TO-DATE
:lib:clean UP-TO-DATE
:lib:preBuild UP-TO-DATE
:lib:preReleaseBuild UP-TO-DATE
:lib:compileReleaseNdk UP-TO-DATE
:lib:compileLint
:lib:copyReleaseLint UP-TO-DATE
:lib:mergeReleaseProguardFiles
:lib:packageReleaseRenderscript UP-TO-DATE
:lib:checkReleaseManifest
:lib:prepareReleaseDependencies
:lib:compileReleaseRenderscript
:lib:generateReleaseResValues
:lib:generateReleaseResources
:lib:packageReleaseResources
:lib:compileReleaseAidl
:lib:generateReleaseBuildConfig
:lib:mergeReleaseShaders
:lib:compileReleaseShaders
:lib:generateReleaseAssets
:lib:mergeReleaseAssets
:lib:processReleaseManifest
:lib:processReleaseResources
:lib:generateReleaseSources
:lib:compileReleaseJavaWithJavac
:lib:processReleaseJavaRes UP-TO-DATE
:lib:transformResourcesWithMergeJavaResForRelease
:lib:transformClassesAndResourcesWithSyncLibJarsForRelease
:lib:mergeReleaseJniLibFolders
:lib:transformNative_libsWithMergeJniLibsForRelease
:lib:transformNative_libsWithSyncJniLibsForRelease
:lib:bundleRelease
:lib:install

BUILD SUCCESSFUL

Total time: 2.616 secs
Gradle exit code 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Found artifact: com.github.tianzhijiexian:lib:1.0.1
EXIT_CODE=0
2016-04-10T15:24:05.669962721Z
Exit code: 0

Build artifacts:
com.github.tianzhijiexian:CommonAdapter-Fake-DataBinding:1.0.1

Files: 
com/github/tianzhijiexian/CommonAdapter-Fake-DataBinding/1.0.1
com/github/tianzhijiexian/CommonAdapter-Fake-DataBinding/1.0.1/CommonAdapter-Fake-DataBinding-1.0.1.aar
com/github/tianzhijiexian/CommonAdapter-Fake-DataBinding/1.0.1/CommonAdapter-Fake-DataBinding-1.0.1.pom
com/github/tianzhijiexian/CommonAdapter-Fake-DataBinding/1.0.1/CommonAdapter-Fake-DataBinding-1.0.1.pom.md5
com/github/tianzhijiexian/CommonAdapter-Fake-DataBinding/1.0.1/CommonAdapter-Fake-DataBinding-1.0.1.pom.sha1
com/github/tianzhijiexian/CommonAdapter-Fake-DataBinding/1.0.1/build.log

**Comment by kaleai** [comment]
fake databinding 项目的整体大小和方法数如下（仅仅是一个空壳，不用担心依赖的大小）：
![qq 20160411112246](https://cloud.githubusercontent.com/assets/9552155/14415984/bfc0589a-ffd7-11e5-90d0-f8da3f479afd.png)

**Comment by kaleai** [comment]
你可以再试试看，如果成了就可以关闭此问题了。

**Comment by xxxifan** [comment]
可以了

**Comment by kaleai** [comment]
我修改了一个编译规则，你看看不依赖db，就只做这条依赖会不会有问题：

```
compile 'com.github.tianzhijiexian:CommonAdapter:ba3ac9bca2'
```

**Comment by xxxifan** [comment]
可以的

**Comment by kaleai** [comment]
好的，感谢测试。这样我又可以帮你去掉了10个方法数
