### ISSUE TITLE
recyclerview设置底部布局, 不会占一列

### ISSUE THREAD

**Issue by xoptimal** [tianzhijiexian/CommonAdapter#31]
设置成GridLayoutManager / StaggeredGridLayoutManager 不会占据一列

我看了代码是你有做处理的, 可是不生效~

**Comment by kaleai** [comment]
我的demo就用到了这个，你看下demo也会这样么？

**Comment by xoptimal** [comment]
这里不能上传图 ...  你的Demo 一样有这样的问题 

`

 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        RecyclerView recyclerView = new RecyclerView(this);
        LayoutUtil.setContentView(this, recyclerView);
        //LinearLayoutManager layoutManager = new LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false);

```
    StaggeredGridLayoutManager layoutManager = new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL);

    recyclerView.setLayoutManager(layoutManager);

    data.addAll(DataManager.loadData(getBaseContext()));
    CommonRcvAdapter<DemoModel> adapter = new CommonRcvAdapter<DemoModel>(data) {
        @Override
        public Object getItemType(DemoModel demoModel) {
            return demoModel.type;
        }

        @NonNull
        @Override
        public AdapterItem createItem(Object type) {
            switch (((String) type)) {
            case "text":
                return new TextItem();
            case "button":
                return new ButtonItem();
            case "image":
                return new ImageItem();
            default:
                throw new IllegalArgumentException("不合法的type");
            }
        }
    };

    final RcvAdapterWrapper wrapper = new RcvAdapterWrapper(adapter, layoutManager);
    Button header = new Button(this);
    header.setText("footview");
    header.setLayoutParams(new ViewGroup.LayoutParams(-1, -1));
    wrapper.setFooterView(header);

    recyclerView.setAdapter(wrapper);

    recyclerView.addOnItemTouchListener(new RcvOnItemClickListener(this, new AdapterView.OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            position = position - wrapper.getHeaderCount();
            if (position >= 0) {
                data.remove(position);
            }
        }
    }));
}
```

`

**Comment by xoptimal** [comment]
你的示例代码, 我换成  StaggeredGridLayoutManager

之前你加的是headerview , 我改成  footview  其余不变 ~  

你可以尝试一下 ,

**Comment by kaleai** [comment]
也就是说demo在你的手机上头部和底部是不能横跨的，对吧。我来看下

**Comment by xoptimal** [comment]
是的,  郁闷半天, 因为之前一直是在用 linearlayoutmanager ..  所以没察觉

**Comment by kaleai** [comment]
你跑的是我最新的代码么？如果不是你可以拉下最新的代码看看

**Comment by xoptimal** [comment]
我引用的,  1.8   不是最新的嘛 ?

**Comment by kaleai** [comment]
你重新拉下最新的，我刚刚提交了一些东西。你看看。没确认问题我不能升版本的

**Comment by kaleai** [comment]
我五天前有提交过

**Comment by xoptimal** [comment]
我勒个去 , 还真好了~  害我瞎折腾一下午 TAT , 

对了, 我想问下你什么时候更新jcenter ....

**Comment by kaleai** [comment]
如果你确定没问题了，我随时可以更新版本号的。如果遇到demo跑起来有问题，直接联系开发者，这明显是开发的问题。如果demo没问题，自己写的代码有问题，那么就可以找找原因。我也很不好意思，抱歉*

**Comment by xoptimal** [comment]
demo还有问题, 滑动到底部刷新了一下 , 然后点击最后的那些view , 抛了异常 

`java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{209b1c33 position=10 id=-1, oldPos=-1, pLpos:-1}`

**Comment by xoptimal** [comment]
刷新那个不是问题,  发觉你后面又跑了一回.....

**Comment by kaleai** [comment]
我来看下整个问题，刷新的那个是我手动做的一个样子

**Comment by kaleai** [comment]
这个我稍后看下，似乎优势recyclerview本身自己状态更新的问题

**Comment by xoptimal** [comment]
我刚是了下, Gridlayoutmanager Gridlayoutmanager  能跨列 ,  但是 StaggeredGridLayoutManager

还是无法跨列,  我以为两个差不多... 后面还是不放心, 果然还是出现了 ...

**Comment by xoptimal** [comment]
并且还有个小问题,  我的footview 设置了 高度的

`footView.setLayoutParams(new ViewGroup.LayoutParams(-1, dip2px(context, 50)));
`

后面还是变成自适应 ....

demo 也是一样

`Button footer = new Button(this);
        footer.setBackgroundColor(getResources().getColor(android.R.color.holo_red_dark));
        footer.setLayoutParams(new ViewGroup.LayoutParams(-1, 500));
        footer.setText("footer");

```
    wrapper.setHeaderView(header);
    wrapper.setFooterView(footer);

    recyclerView.setAdapter(wrapper);`
```

**Comment by xoptimal** [comment]
设置高度的问题,

 private static class SimpleViewHolder extends RecyclerView.ViewHolder {

```
    public SimpleViewHolder(View itemView) {
        super(itemView);
       /* itemView.setLayoutParams(new ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT
        ));*/
    }
}
```

我改成宽高都是MATCH_PARENT, MATCH_PARENT  也是无法解决 

故, 我直接去掉了该设置, 不进行设置layoutparams 即可,

**Comment by xoptimal** [comment]
我可以问下进度吗 0,0

**Comment by kaleai** [comment]
现在已经复现了你的问题，我一有空就解决。这个是很严重的问题，我肯定会快速解决的。

**Comment by kaleai** [comment]
当然，如果你也发现了原因，可以给我说。

**Comment by kaleai** [comment]
我现在在修复另一个工程的bug，所以暂时时间不是很多。

**Comment by xoptimal** [comment]
我尝试解决, 不过, 好像还是不行 ...  于是我参考了别人的解决方案 .

是可行的,  但是, 不知道是数据加载的原因, 还是加载view的整个流程 ....

进来的第一次, 还是无法扩列,    但是我刷新后就正常了 ....   

我把我的参考的项目发给你吧...

https://github.com/cundong/HeaderAndFooterRecyclerView

它对 ExStaggeredGridLayoutManager 单独写了处理方式,

重新走了onMeare ..

关键代码:

`
 @Override
    public void onMeasure(RecyclerView.Recycler recycler, RecyclerView.State state, int widthSpec, int heightSpec) {
        //Log.d(TAG, "item count = " + getItemCount());
        for (int i = 0; i < getItemCount(); i++) {

```
        if (mSpanSizeLookup.getSpanSize(i) > 1) {
            //Log.d(TAG, "lookup > 1 = " + i);
            try {
                //fix 动态添加时报IndexOutOfBoundsException
                View view = recycler.getViewForPosition(i);
                if (view != null) {
                    /**
                     *占用所有的列
                     * @see https://plus.google.com/+EtienneLawlor/posts/c5T7fu9ujqi
                     */
                    StaggeredGridLayoutManager.LayoutParams lp = (StaggeredGridLayoutManager.LayoutParams) view.getLayoutParams();
                    lp.setFullSpan(true);
                }
                // recycler.recycleView(view);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    super.onMeasure(recycler, state, widthSpec, heightSpec);
}
```

`

**Comment by kaleai** [comment]
这个不就是我之前工程的代码么？

**Comment by xoptimal** [comment]
这个也是你写的嘛 0.0

**Comment by kaleai** [comment]
这个代码竟然还是我写的：
![image](https://cloud.githubusercontent.com/assets/9552155/15035213/073fe2fc-12b2-11e6-990a-a82611c9ddb2.png)

**Comment by xoptimal** [comment]
噗, 我没注意这个耶 ~

**Comment by kaleai** [comment]
这个的写法我认为是不合适的，所以最后就抛弃了。没关系，我再看看。

**Comment by xoptimal** [comment]
巧了 ~ 嘿嘿,  看来这个问题还得你来解决啊 , 哈哈 ~

**Comment by xoptimal** [comment]
我又发觉了个小问题 , 我的layoutmanager  

本来的是 LinearLayoutManager, 通过按钮切换成 GridLayoutManager

本来呢,   GridLayoutManager 是可以扩列了, 切换又不行了~

**Comment by kaleai** [comment]
头部和底部无法设置高度的问题已经解决。

头部底部第一次无法跨列的问题不能复现。

头部底部在切换layoutmanager的时候无法跨列，是已知问题。
原因是切换layoutmanager后重新布局，不会保留之前的滚动位置的。头部和底部的布局是要通过adapter的wraper进行一次性设置的。如果直接切换layoutmanager是无法对头部和底部进行修改的。所以如果要切换layoutmanager就需要重新设置adapter。如果要实现动态切换，并且没问题，那么就必须每次切换layout的时候都去判断是否要跨列。这是我早期的写法，我觉得效率是很低的。

添加底部后点击最后一个item会崩溃的问题。
这个问题在不添加那个wraper的时候是不会出现的，即使是用了那个wraper只添加头也没用问题。当添加了底部，并且删除最后一个item的时候就会出现这个异常。具体可以看：https://code.google.com/p/android/issues/detail?id=82199 

我用了一个不舒服的方法解决了，我在找更好的方案。

**Comment by xoptimal** [comment]
刚更新代码,  run 起来 .... 还是无法扩列 ....

**Comment by xoptimal** [comment]
`

 protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        final RecyclerView recyclerView = new RecyclerView(this);
        LayoutUtil.setContentView(this, recyclerView);

```
    //LinearLayoutManager layoutManager = new LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false);

   // GridLayoutManager layoutManager1 = new GridLayoutManager(this, 2);


    StaggeredGridLayoutManager layoutManager1 = new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL);

    recyclerView.setLayoutManager(layoutManager1);

    data.addAll(DataManager.loadData(getBaseContext()));

    CommonRcvAdapter<DemoModel> adapter = new CommonRcvAdapter<DemoModel>(data) {
        @Override
        public Object getItemType(DemoModel demoModel) {
            return demoModel.type;
        }

        @NonNull
        @Override
        public AdapterItem createItem(Object type) {
            switch (((String) type)) {
                case "text":
                    return new TextItem();
                case "button":
                    return new ButtonItem();
                case "image":
                    return new ImageItem();
                default:
                    throw new IllegalArgumentException("不合法的type");
            }
        }
    };

    final RcvAdapterWrapper wrapper = new RcvAdapterWrapper(adapter, layoutManager1);

    Button header = new Button(this);
    header.setText("Header");

    Button footer = new Button(this);
    footer.setBackgroundColor(getResources().getColor(android.R.color.holo_red_dark));
    footer.setLayoutParams(new ViewGroup.LayoutParams(-1, 500));
    footer.setText("footer");

    wrapper.setHeaderView(header);
    wrapper.setFooterView(footer);

    recyclerView.setAdapter(wrapper);
```

`

**Comment by xoptimal** [comment]
动态切换的话,  看来还是得按重新一个个判断才行, 否则无法实现需要的效果,

在wrapper 里面, 你是在构造器里面就判断 layoutmanager ... 我建议是抽出来做成方法.

可是在后面被调用 ... 我现在的处理方式是如下:

我提供了一个setlayoutmanager() 方法, 用于动态切换 ...

话说, 假设重新setadapter , 就会出现白屏一下子的情况

`public void setLayoutManager(final RecyclerView.LayoutManager layoutmanager) {

```
    //mRecyclerView.setAdapter(mWrapper);
    mRecyclerView.setLayoutManager(layoutmanager);

    if (layoutmanager instanceof GridLayoutManager) {

        ((GridLayoutManager) layoutmanager).setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            public int getSpanSize(int position) {
                int type = mWrapper.getItemViewType(position);
                return type != 99930 && type != 99931 ? 1 : ((GridLayoutManager) layoutmanager).getSpanCount();
            }
        });
    }
}`
```

**Comment by xoptimal** [comment]
这个效率很低 , 估计无法避免的吧  ?

**Comment by kaleai** [comment]
如果你这么做了你可以试试反复切换的情况，从grid切换到steg，然后再切回来。我尝试后发现会出现界面的布局异常。无法跨列这个是一进去就不行，还是你点了什么后不行。

**Comment by xoptimal** [comment]
StaggeredGridLayoutManager   只有这个layoutmanager 无法扩列, 

默认第一次就设置了这个,  一进去就不行 ...

**Comment by kaleai** [comment]
你什么手机，换个手机试试。。。

**Comment by xoptimal** [comment]
小米 ~

**Comment by kaleai** [comment]
LinearLayoutManager layoutManager = new LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false);
        GridLayoutManager layoutManager1 = new GridLayoutManager(this, 2);
        recyclerView.setLayoutManager(layoutManager1);

我的代码是一进来设置的是grid的manager，默认是这个

**Comment by xoptimal** [comment]
我改了你的demo ,  换成了默认是 StaggeredGridLayoutManager

**Comment by xoptimal** [comment]
目前我切换的只有这2种: LinearLayoutManager  和 GridLayoutManager 

来回切换没存在布局错乱的问题,

**Comment by kaleai** [comment]
给我看下你的切换的代码

**Comment by xoptimal** [comment]
我上面贴过了,  就是那个setlayoutManager() 这个方法,

**Comment by kaleai** [comment]
如果你测试没问题，可以提交pr

**Comment by xoptimal** [comment]
来回切换很多次,  均未出现错乱现象 ...

刚好在公司,  拿了其他机子测试 ,  HTC也是如此 ~

StaggeredGridLayoutManager 还是无法扩列 ~

**Comment by xoptimal** [comment]
pr 不至于, 小事情 ~

**Comment by xoptimal** [comment]
那里我也建议了, 你在wrapper 里就有判断了,  只不过我觉得那里不适合.

你可以抽取出来做成setlayoutmanager() 方法,  这样扩展性更高一些了

**Comment by kaleai** [comment]
我建议你可以把你的代码提交上来，然后我看下。

**Comment by xoptimal** [comment]
现在主要还是StaggeredGridLayoutManager 跨列的问题,  估计不是机型问题 ..

**Comment by kaleai** [comment]
那个小问题，可能是哪里改错了。我现在没时间看，稍后看看

**Comment by kaleai** [comment]
艹，会不会是appcompat升级的问题！

**Comment by xoptimal** [comment]
噗~  不会那么邪吧 , 这个我不清楚耶 ~

我当前版本 `compile 'com.android.support:appcompat-v7:23.3.0'`

**Comment by xoptimal** [comment]
从未 pr  过 ,   我copy 到我的项目来, 然后改了... 然后也提交了....

可是没找到哪里发给你的,  英语不好 0.0  菜鸟一个 TAT

**Comment by kaleai** [comment]
问题已经修复，你测试一下。

**Comment by xoptimal** [comment]
OK  , 验证过了,  没问题

**Comment by xoptimal** [comment]
我看你还加了个注解....

**Comment by xoptimal** [comment]
我还有个问题, 你去看看 ...

**Comment by xoptimal** [comment]
期待你更新到 jcenter ~ thanks ,   最后, 非常希望改善下wrapper ...

就是我上回提出的扩展性问题,  以及注解用并不是很多 , 建议能去掉就去掉吧 ...

**Comment by kaleai** [comment]
你可以吧你提供的wrapper扩展的代码贴一下

**Comment by kaleai** [comment]
最新的代码已经支持了你要的setLayoutmanager，请测试一下。

**Comment by xoptimal** [comment]
我测试一下,   我记得有点问题的,  不知道你的会不会有这样的情况~

**Comment by xoptimal** [comment]
果然, 还是不会扩列~  我把我写的那个出来 ~

很抱歉, 最近玩去了,

**Comment by xoptimal** [comment]
果然还是有问题, 这个问题是GridLayoutManager 引起的,  切换, 无法扩列

**Comment by xoptimal** [comment]
我把改动的部分贴出来给你把 ~

第一部分(构造器):  

```
public RcvAdapterWrapper(RecyclerView.Adapter adapter, @NonNull RecyclerView.LayoutManager layoutManager) {
        mWrapped = adapter;
        mWrapped.registerAdapterDataObserver(new RecyclerView.AdapterDataObserver() {
            @Override
            public void onChanged() {
                notifyDataSetChanged();
            }

            @Override
            public void onItemRangeChanged(int positionStart, int itemCount) {
                notifyItemRangeChanged(positionStart + getHeaderCount(), itemCount);
            }

            @Override
            public void onItemRangeInserted(int positionStart, int itemCount) {
                notifyItemRangeInserted(positionStart + getHeaderCount(), itemCount);
            }

            @Override
            public void onItemRangeRemoved(int positionStart, int itemCount) {
                notifyItemRangeRemoved(positionStart + getHeaderCount(), itemCount);
                if (getFooterCount() != 0) {
                    if (positionStart + getFooterCount() + 1 == getItemCount()) { // last one
                        notifyDataSetChanged();
                    }
                }
            }

            @Override
            public void onItemRangeMoved(int fromPosition, int toPosition, int itemCount) {
                // TODO: 2015/11/23 还没支持"多个"item的转移的操作 
                notifyItemMoved(fromPosition + getHeaderCount(), getHeaderCount() + toPosition);
            }
        });
        setLayoutManager(layoutManager);
    }
```

第二部分(setlayoutmanager):

```
public void setLayoutManager(RecyclerView.LayoutManager layoutManager) {

        this.layoutManager = layoutManager;

        if (layoutManager instanceof StaggeredGridLayoutManager) {

            if (headerView != null) {
                setFullSpan(headerView, layoutManager);
            }

            if (footerView != null) {
                setFullSpan(footerView, layoutManager);
            }

        } else if (layoutManager instanceof GridLayoutManager) {

            final GridLayoutManager gridLayoutManager = (GridLayoutManager) layoutManager;

            gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                public int getSpanSize(int position) {
                    int type = getItemViewType(position);
                    return type != TYPE_HEADER && type != TYPE_FOOTER ? 1 : gridLayoutManager.getSpanCount();
                }
            });
        }
    }
```

第三部分(setFullSpan): 

```
private void setFullSpan(View view, RecyclerView.LayoutManager layoutManager) {

        StaggeredGridLayoutManager.LayoutParams layoutParams = new StaggeredGridLayoutManager.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        layoutParams.setFullSpan(true);
        view.setLayoutParams(layoutParams);
    }
```

**Comment by xoptimal** [comment]
为什么我贴的代码, 明明放到 `` 这里面, 还是乱的很夸张 ...

**Comment by xoptimal** [comment]
代码我是测试过了, 没有问题, 你可以尝试一下

完了, 我建议该更新一个jcenter版本了 ~

**Comment by kaleai** [comment]
好，我周一就更新
