### ISSUE TITLE
可否增加recyclerviewAdater的单选多选

### ISSUE THREAD

**Issue by fg2q1q3q** [tianzhijiexian/CommonAdapter#32]
可否增加recyclerviewAdater的单选多选功能

**Comment by kaleai** [comment]
这个adapter的目的是达到解耦和方便使用扩展，并不是想要做万能的adapter。如果增加了那些功能，这个东西就不纯粹了，而且引入成本也很高。所以我希望你可以在用单选的时候自己进行组合来做，或者是用别的库做一下。
