### ISSUE TITLE
为什么不能添加依赖？

### ISSUE THREAD

**Issue by 574085757** [tianzhijiexian/CommonAdapter#34]
Error:Could not find com.github.tianzhijiexian:CommonAdapter:Latest release.
Required by:
    Breaktrip1:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>``

**Comment by kaleai** [comment]
latest release 要做替换的

**Comment by 574085757** [comment]
哦，我明白了，谢谢
