### ISSUE TITLE
可不可以不混淆IAdapter

### ISSUE THREAD

**Issue by xxxifan** [tianzhijiexian/CommonAdapter#35]
不是什么大问题，只是每次new CommonxxAdapter的时候，createItem方法的参数是一个Object o，看起来有点迷惑

**Comment by kaleai** [comment]
这个不算是混淆，而是在打包的时候自动做的处理，这个我也没啥好办法。

**Comment by xxxifan** [comment]
确实是  我就说怎么其他都没做处理  唯独这些interface没有了默认变量名

**Comment by kaleai** [comment]
我再看看又没啥办法吧。我记录一下。
