### ISSUE TITLE
RecyclerView MemoryLeak

### ISSUE THREAD

**Issue by hkllzh** [tianzhijiexian/CommonAdapter#40]
> 问题如下
- 继承`CommonRcvAdapter`
- 多个item type
- 在任意item里面

```
@Override
public void handleData(Object o, int position) {
    Glide.with(mFrg).load("http://xxx.png").into(imageview);
}
```

也就是在单个item里面使用Glide加载图片，本来图片宽`match_parent`，高`135dp`固定值。

这样程序内存一直增加，看情况是view不停在绘制。注释加载图片代码，情况恢复正常。

**Comment by hkllzh** [comment]
# **Sorry**
1. 经过测试是由于另外一个item有`ViewPager`并且使用了自动滑动引起的布局重绘。手动滑动也会引起布局重绘。
2. 不过同时item类型分辨方法没有生效。

修改为如下：
把`ItemTypeUtil`类的`SparseArray`用`ArrayList`替代，即可防止重绘的时候多类型判断实效。
不过单独测试`SparseArray`的`indexOfValue`方法可以正常使用，在程序里面`indexOfValue`方法，及时集合中有一个对象，依然返回-1。这个时候`ArrayList`的`indexOf`可以正常使用。

**Comment by kaleai** [comment]
也就是说那个类型获取器有些问题吧，换成arraylist解决的话，可能是因为sparseArray的key和ArrayList的key判断逻辑有差异，一个是用了equals()，一个是用了==来判断。感觉你的问题比较复杂，可以加460412008@qq.com聊一下。希望可以帮你解决

**Comment by kaleai** [comment]
这个问题我先换为arraylist做处理，然后你看下是否能解决。近期我会提交一次代码。

**Comment by JWBlueLiu** [comment]
我现在改成这样
用arraylist
然后获取classname
这样就不需要有itemtype方法
另外list里面可以放各种类型数据

**Comment by kaleai** [comment]
``` JAVA
    /**
     * @param type item的类型
     * @return 通过object类型的type来得到int类型的type
     */
    @VisibleForTesting
    public int getIntType(Object type) {
        int index = typeList.indexOf(type);
        if (index == -1) {
            index = typeList.size();
            // 如果没用这个type，就存入这个type
            typeList.add(index, type);
        }
        return index;
    }
```

@hkllzh @JWBlueLiu  我用list进行了实现
