### ISSUE TITLE
如何动态的设置List来实现更多加载或者上拉刷新功能

### ISSUE THREAD

**Issue by chenleicpp** [tianzhijiexian/CommonAdapter#41]
我看例子程序只有在初始化的时候传入List，在获取数据过程中有没有接口来刷新数据？

**Comment by kaleai** [comment]
你看的例子是mvvm的自动绑定的例子，那个已经实现了list变界面自动刷新的功能了。如果你要用普通的方式，可以使用IAdapter#setData(list<T> list)方法来做。如果我理解错了，请和我说下哈。
