### ISSUE TITLE
RecyclerView加载数据显示不完全。

### ISSUE THREAD

**Issue by Clearlee** [tianzhijiexian/CommonAdapter#43]
你好，我在使用您提供的CommonRcvAdapter时，按照Demo的例子自定义，改写了一下布局，但是现在有个问题，RecyclerView经常不会把数据加载完全，很多时候都只能加载一部分，另外的显示的全是空白。请问这是什么原因引起的呢？

加载代码：
final List<DemoModel> data = DataManager.loadData(MainActivity.this);
Log.i(TAG, "data.size = " + data.size());   //size显示是正常的
((CommonRcvAdapter<DemoModel>) mRecyclerView.getAdapter()).setData(data); // 设置新的数据
mRecyclerView.getAdapter().notifyDataSetChanged(); // 通知数据刷新

代码可以查看https://github.com/Clearlee/GoKitchen

**Comment by kaleai** [comment]
如果demo 没问题，那么就先定位下布局的问题吧。你可以借给图给我么，看代码的话太细了。

**Comment by Clearlee** [comment]
打扰了，不知道怎么上次评论图片，所有给你发了封邮件

**Comment by Clearlee** [comment]
上传。。。。。

**Comment by kaleai** [comment]
460412008@qq.com

**Comment by kaleai** [comment]
看下你的item的布局是match_parent还是wrap_content

**Comment by Clearlee** [comment]
OK了，非常感谢。我的天。。。居然犯这种愚蠢的错误。。。。。。

**Comment by kaleai** [comment]
没事的，谁都会犯错的。这以后不就有经验了么，我能这么快的猜想到，也是因为之前犯错了。很高兴与你交流，你觉得这个库咋样。
