### ISSUE TITLE
ViewHolder中的item问题

### ISSUE THREAD

**Issue by ValuesFeng** [tianzhijiexian/CommonAdapter#44]
来，看截图，这中间的item是一个接口对吧。

![image](https://cloud.githubusercontent.com/assets/7418605/19799134/988521aa-9d27-11e6-9c58-691c498e055f.png)

ok,继续，如果我的情况是一个viewpager ，里面各种recyclerview，我现在需要给rv加载RecyclerPool。
就有问题了。

![image](https://cloud.githubusercontent.com/assets/7418605/19799278/636db648-9d28-11e6-8754-df68ab3e5b59.png)

这里面的holder是被会复用的，那么，如果holder被复用的情况下， 如果保证holder中的item正确指向呢？

**Comment by ValuesFeng** [comment]
![image](https://cloud.githubusercontent.com/assets/7418605/19799361/cc27cdc2-9d28-11e6-96b7-c32a6dd7e307.png)

咱们看log，  item的type是focus_product，但是出现了调用了上个pool中的banner。

**Comment by ValuesFeng** [comment]
虽然可以holder.item = createItem(mType)来解决这个问题，
but  性能……   本身就要用pool来降低viewhold的创建的。

**Comment by kaleai** [comment]
item是在viewholder的初始化中传入的，vh是复用的，item也是和它一起复用的。你可以先用官方写法，看看是否会出现这样的问题。然后也希望可以贴一下具体的流程，和你的需求，我可以针对性的进行修复。感谢反馈。

**Comment by ValuesFeng** [comment]
嗯   其实需求很简单   就是Viewpager 中的recyclerview公用一个recyclerpool     ～ pool池复用vh的时候出现问题

**Comment by kaleai** [comment]
我460412008，加个qq吧。咱们有空就调一下哈

**Comment by ValuesFeng** [comment]
刚才发现一个严重问题，viewholder没有复用，不知道你那边是不是？

**Comment by ValuesFeng** [comment]
![image](https://cloud.githubusercontent.com/assets/7418605/20738765/81908ee8-b6f0-11e6-9f2c-cc18f52a991e.png)

大哥，情何以堪。。
刚才看下了ItemTypeUtil，为什么是SparseArray 或者 ArrayList，如果真的需要考虑存取速度，直接放HashMap吧。

**Comment by kaleai** [comment]
fixed
