### ISSUE TITLE
如何更新Item构造函数中传入的的非泛型数据呢？

### ISSUE THREAD

**Issue by Andecy** [tianzhijiexian/CommonAdapter#48]
有这样一个需求，通过Item的构造函数传入一个T1类型数据，然后Item指定的泛型是T，现在update或者setData的时候，只能改T，请问怎么改T1呢？

**Comment by kaleai** [comment]
public class Item<T> extends AdapterItem<T>{

handleData(T data, int position);

}
这样？

**Comment by Andecy** [comment]
是的，类似这样，然后怎么通过adapter调用那个handleData这个方法呢？

**Comment by kaleai** [comment]
adapter本身是间接调用handlerData方法啊，这个自动会调用的。如果不清楚加460412008

**Comment by Andecy** [comment]
沟通后可以了，大概就是需要有一个类，去让Item和当前的页面同时持有，然后去更新这个类下面的属性
