### ISSUE TITLE
RecycleView RecycleViewPool 中存在内存泄漏，每次显示时候RecycleViewPool 中RcvAdapterItem会增加。

### ISSUE THREAD

**Issue by maoqis** [tianzhijiexian/CommonAdapter#49]
不知道有没有碰到这个问题。RcvAdapterItem会缓存很多。正常情况下只有2个缓存。不知道哪里出现内存泄漏导致Pool中 RcvAdapterItem 很快的积累很多。

**Comment by kaleai** [comment]
你是在用了RecycleViewPool的情况下出现的这个问题吧，多个页面共享了item后，pool中item增加速度很快，是这样吧？

**Comment by maoqis** [comment]
是的。发现问题原因了 。不能使用CommonRcvAdapter里面的public Object getItemType(T t)；
源码中把类型 使用同一个全局变量private Object mType存储公用可能有问题。滑动太快应该会出现同步问题。刚解决的还没怎么确认。希望能改进下。

**Comment by maoqis** [comment]
可能adapter原来是基于ListView. 这块recycleView确实存在问题。建议type 让用户自己扩展。或者存到Bean里面。每次从dataList 中获取bean 再获取type。

**Comment by kaleai** [comment]
@ValuesFeng 这个可以看一下

**Comment by kaleai** [comment]
@maoqis 可以加460412008，了解下具体的情况，如果可以，那么可以提交pr

**Comment by ValuesFeng** [comment]
@maoqis   之前我提交了一份PR，没太看懂你的描述。你是在初始化的时候item加载很多么？另外，2个缓存是指什么？item的缓存个数根据你的屏幕有多少个以及viewpager预加载的时候，其他fragment的item个数来决定的呀。
内存泄漏倒是不应该，应该是内存溢出了。

**Comment by ValuesFeng** [comment]
@maoqis   你用的是官方的Pool还是[RecyclerViewPool](https://github.com/ValuesFeng/CommonAdapter/blob/master/adapter/src/main/java/kale/adapter/component/RecycledViewPool.java)？

**Comment by kaleai** [comment]
我感觉是在getItemType的时候，直接返回的是data。这个data是list中的某个对象，这样就会出现每个对象都不同，type个数无限增加的情况。

感觉可以在utils中进行判断，如果不是基础对象，那么就变成对象的class作为type

**Comment by maoqis** [comment]
我感觉是在getItemType的时候，直接返回的是data。这个data是list中的某个对象，这样就会出现每个对象都不同，type个数无限增加的情况。
应该就是这个原因。

**Comment by maoqis** [comment]
github 不太会用比较抱歉。看到问题已经解决了。想了想就是 每个对象对应了不同的type。
