### ISSUE TITLE
依赖失败

### ISSUE THREAD

**Issue by wwzlp** [tianzhijiexian/CommonAdapter#55]
当前这个库依赖失败。我这边有缓存可以，其他工程我试了下都不行，任何版本。其他同事那边试过也不行，连接不上。昨天打包还OK的。

**Comment by kaleai** [comment]
报错日志发一下，我查一下问题。可能是jitpack的问题

**Comment by wwzlp** [comment]
![image](https://cloud.githubusercontent.com/assets/8874308/22765534/d76b9518-eeab-11e6-8c98-71fa345ea83f.png)

**Comment by kaleai** [comment]
好的，我马上看一下。加我qq吧，460412008

**Comment by kaleai** [comment]
2.2.1可以的
