### ISSUE TITLE
debug版本无法运行

### ISSUE THREAD

**Issue by swxca** [tianzhijiexian/CommonAdapter#57]
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by swxca** [comment]
[已解决，方法在这里](http://stackoverflow.com/questions/37004069/errorjack-is-required-to-support-java-8-language-features)

**Comment by kaleai** [comment]
这里你是用的1.8吧
