### ISSUE TITLE
2.2.1 依赖失败

### ISSUE THREAD

**Issue by swxca** [tianzhijiexian/CommonAdapter#58]
![image](https://cloud.githubusercontent.com/assets/11407831/23739828/be690276-04db-11e7-80da-05c01a740d69.png)

**Comment by swxca** [comment]
![image](https://cloud.githubusercontent.com/assets/11407831/23739926/21222cc6-04dc-11e7-8db5-8fa4e956087d.png)

**Comment by MaYunFei** [comment]
项目根目录的 `gradle`
```gradle
repositories {
    maven {
        url "https://jitpack.io"
    }
}
```
检查一下

**Comment by kaleai** [comment]
![image](https://cloud.githubusercontent.com/assets/9552155/23778442/25cf926a-0575-11e7-8852-c9d2f2ba3d7e.png)

你 依赖错了版本号了
