### ISSUE TITLE
如何更新dataList

### ISSUE THREAD

**Issue by JWBlueLiu** [tianzhijiexian/CommonAdapter#6]
点击了某个item 对应的DemoModel 也要进行update 有什么好办法吗

**Comment by kaleai** [comment]
为啥关闭了呢，这个问题虽然和这个库无关，但是我可以给出一个建议。就是点击后在item中截获点击事件，然后updatemodel

**Comment by JWBlueLiu** [comment]
因为我知道怎么弄了 待会弄一个Pull requests

**Comment by kaleai** [comment]
好的，感谢。
