### ISSUE TITLE
关于adapter的源码 少了个类 DemoItemImageBinding

### ISSUE THREAD

**Issue by txc1223** [tianzhijiexian/CommonAdapter#8]
import kale.commonadapter.databinding.DemoItemImageBinding;

这个类没有找到哦。是不是被删了？

**Comment by txc1223** [comment]
不知为何能运行了 点进这个类竟然是个布局文件。

**Comment by kaleai** [comment]
这里利用了dataBinding这个库

**Comment by txc1223** [comment]
我知道啊，但是这个kale.commonadapter.databinding.DemoItemImageBinding类应该是你写的吧？我怎么没有找到这个java文件呢？

**Comment by kaleai** [comment]
这是库自动生成的，你看不到的。不是我写的

**Comment by txc1223** [comment]
好吧，谢谢
