### ISSUE TITLE
何時會釋出1.1.5或更新版呢？

### ISSUE THREAD

**Issue by NeoLSN** [tianzhijiexian/CommonAdapter#9]
1.1.4之後又做了更新
與1.1.4相比有了大幅度的改動
何時會釋出呢？

**Comment by kaleai** [comment]
最近正在databinding的适配，还增加了对viewpager的适配器。我现在去提交个较为稳定版本，谢谢你的支持。我可能是今明就会有个新的提交

**Comment by kaleai** [comment]
1.4之后提交的部分代码主要是增加了对viewpager的适配器支持，所以改动较大。但实际上对外暴露的接口是几乎一致的，仅仅是改了下名字。这点我以后会多注意的，尽量对这些不做改动。这回也是迫不得已。

**Comment by kaleai** [comment]
我现在已经支持了db，准备修改下readme后就可以发布1.1.5了。

**Comment by NeoLSN** [comment]
加油 期待更新版

**Comment by wuya1111** [comment]
RecyclerView use  CommonAdapter  The load more abnormal

**Comment by jiezili** [comment]
关于对viewpager的适配器支持，简单测试发现有错位情况，还没来得及分析具体原因

**Comment by kaleai** [comment]
viewpager的测试还在进行，目前是支持了懒加载和自动复用item。希望先测试其他adapter的问题，viewpager的我去详细看看。感谢支持。
现在的adapter还支持数据拆包，可以支持多个接受不同数据对象的item结构。文档会稍后补充。

**Comment by kaleai** [comment]
@wuya1111 能具体描述下问题么，或者给个demo。我来看看

**Comment by kaleai** [comment]
#11 是viewpager的问题，viewpager的适配器问题可以在那里继续提问。此问题因为过于抽象，故准备关闭。
